[package]
name = "zdc-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "zdc"
path = "src/main.rs"

[dependencies]
clap.workspace = true
zdc-ast = { path = "../zdc-ast" }
zdc-codegen = { path = "../zdc-codegen" }
zdc-dev = { path = "../zdc-dev" }
zdc-diagnostics = { path = "../zdc-diagnostics" }
zdc-graph = { path = "../zdc-graph" }
zdc-hir = { path = "../zdc-hir" }
zdc-parser = { path = "../zdc-parser" }
zdc-resolve = { path = "../zdc-resolve" }
zdc-types = { path = "../zdc-types" }
