[package]
name = "zdc-diagnostics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ariadne.workspace = true
zdc-codegen = { path = "../zdc-codegen" }
zdc-graph = { path = "../zdc-graph" }
zdc-lexer = { path = "../zdc-lexer" }
zdc-parser = { path = "../zdc-parser" }
zdc-resolve = { path = "../zdc-resolve" }
zdc-types = { path = "../zdc-types" }
